# Set the build language to Python
language: python

# Set the python version to 3.6
python:
- '3.6'

# Install dependencies
install:
- python -m pip install pytest

# Run tests
script:
- python -m pytest test_rps.py test_fizzbuzz.py -v

# Install the codecov pip dependency
install:
  - pip install codecov

# Run the unit test
script:
  - coverage run test_rps.py test_fizzbuzz.py

# Push the results back to codecov
after_success:
  - codecov --token=d19494ac-7469-4236-9e88-e32270f9950c
